apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mw-guestbook
spec:
  destination:
    namespace: grupp2
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://github.com/SvartaStorken/argo_guestbook.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true